version: "2.6"

services:

  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: 'new_value'

  app:
    build: .
    entrypoint: /code/entrypoint.sh
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./:/code
    depends_on:
      - postgres
