# Generated by Django 4.0.6 on 2022-07-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_course_name_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='type_of_person',
            new_name='type',
        ),
    ]
