# Generated by Django 4.0.6 on 2022-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_rename_type_of_person_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='social_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
