# Generated by Django 4.0.6 on 2022-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_person_social_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], max_length=30),
        ),
    ]
