# Generated by Django 4.0.6 on 2022-07-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_course_group_course_subject_person_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
